apiVersion: v1
kind: Service
metadata:
  name: kagent-ui-nodeport
  namespace: kagent
  labels:
    app.kubernetes.io/name: kagent-ui
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: kagent
    app.kubernetes.io/component: ui
  ports:
    - name: ui
      port: 8080
      targetPort: 8080
      nodePort: 30808
      protocol: TCP
