apiVersion: v1
kind: Service
metadata:
  name: vault-ui-nodeport
  namespace: vault
  labels:
    app.kubernetes.io/name: vault
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: vault
    component: server
  ports:
    - name: http
      port: 8200
      targetPort: 8200
      nodePort: 30820
      protocol: TCP
